---
- name: Ensure if redis is previously installed or not
  stat:
    path: "/usr/local/bin/redis-server"
  register: redis_status

- name: Ensure that the defined redis version is downloaded {{ redis_version }}
  unarchive:
    src: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
    dest: /tmp/
    remote_src: yes
  when: >
    not redis_status.stat.exists or
    upgrade_redis

- name: Ensure the build time dependencies are met
  make:
    chdir: "/tmp/redis-{{ redis_version }}"
  when: >
    not redis_status.stat.exists or
    upgrade_redis

- name: Ensuring the redis server is installed
  make:
    chdir: "/tmp/redis-{{ redis_version }}"
    target: install
  when: >
    not redis_status.stat.exists or
    upgrade_redis
