---
- name: Checking redis hosts are defined or not
  fail:
    msg: "Setup execution failed due to missing group"
  when: >
    groups['redis_cluster'] is not defined and
    groups['redis'] is not defined and
    groups['sentinel'] is not defined

- name: Ensuring OS is supported by the automation
  fail:
    msg: "Setup execution failed because the {{ ansible_os_family }} is not supported"
  when: >
    ansible_os_family != "Debian" and
    ansible_os_family != "RedHat"
