---
- name: Ensure if exporter is previously installed or not
  stat:
    path: "/usr/local/bin/redis_exporter"
  register: exporter_status

- name: Ensure that the defined exporter version is downloaded  # {{ redis_version }}
  unarchive:
    src: https://github.com/oliver006/redis_exporter/releases/download/v1.45.0/redis_exporter-v1.45.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes
  when: >
    not exporter_status.stat.exists or
    upgrade_redis

- name: Copy file with owner and permissions
  copy:
    src: /tmp/redis_exporter-v1.45.0.linux-amd64/redis_exporter
    dest: /usr/local/bin/
    # owner: foo
    # group: foo
    # mode: '0644'
