---
- name: Ensure if exporter is previously installed or not
  stat:
    path: "/usr/local/bin/exporter"
  register: exporter_status

- name: Ensure that the defined exporter version is downloaded  # {{ redis_version }}
  unarchive:
    src: https://github.com/oliver006/exporter/releases/download/v1.45.0/exporter-v1.45.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes
  when: >
    not exporter_status.stat.exists 

- name: Copy file with owner and permissions
  copy:
    src: /tmp/exporter-v1.45.0.linux-amd64/exporter
    dest: /usr/local/bin/
    remote_src: yes
    owner: root
    group: root
    # mode: '0644'
