---
- name: Download redis artifact
  unarchive:
    src: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
    dest: /opt/
    remote_src: yes

- name: Build runtime dependencies for redis
  make:
    chdir: /opt/redis-{{ redis_version }}

- name: Install redis server
  make:
    chdir: /opt/redis-{{ redis_version }}
    target: install

- name: Deleting the downloaded redis package
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/opt/redis-{{ redis_version }}.tar.gz"
    - "/opt/redis-{{ redis_version }}"

- name: Creating group for redis
  group:
    name: "redis"
    state: present

- name: Creating system user for redis
  user:
    name: "redis"
    group: "redis"
    shell: /sbin/nologin
    password: "!!"
    createhome: no
    system: yes
    state: present

- name: Creating logfile directory for standalone setup
  file:
    path: "{{ redis_log_dir }}"
    state: directory
    recurse: yes
    owner: redis
    group: redis

- name: Creating redis data directory
  file:
    path: "{{ redis_dir }}"
    state: directory
    recurse: yes
    owner: redis
    group: redis

- name: create "{{ redis_conf_file_location }}" directory
  file:
    path: "{{ redis_conf_file_location }}"
    state: directory
    recurse: yes
    owner: redis
    group: redis
