---
- name: Checking Pre-Requisities
  include: check-prerequisities.yml

- name: Configure OS level packages
  include: configure-packages.yml

- name: Install and configure redis with common configuration
  include: install-configure.yml

- name: Configure standalone Redis Server
  include: standalone.yml
  when: >
    inventory_hostname in groups['standalone']

- name: Configure Redis master
  include: master.yml
  when: >
    inventory_hostname in groups['master_nodes']

- name: Configure Redis master
  include: slave.yml
  when: >
    inventory_hostname in groups['slave_nodes']
