---
- name: Start Redis Service
  systemd:
    name: redis.service
    enabled: yes
    state: restarted

- name: Start Redis Master Service
  systemd:
    name: redis-master.service
    enabled: yes
    state: restarted

- name: Start Redis Slave Service
  systemd:
    name: redis-slave.service
    enabled: yes
    state: restarted

- name: "restart sentinel"
  service:
    name: sentinel_{{ redis_sentinel_port }}
    state: restarted
  when: redis_as_service
    
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
