---
- name: Ensure system daemon reloaded
  systemd:
    daemon_reload: yes
  become: yes

- name: Ensure sentinel service is running
  systemd:
    name: redis-sentinel.service
    enabled: yes
    state: restarted
  become: yes
