---
- hosts: redis
  roles:
    - { role: redis, tags: ["preinstall", "redis"] }

- hosts: redis_cluster
  vars:
    redis_password: Opstree@1234
    leader_redis_port: 6379
    follower_redis_port: 6380
  tasks:
    - include: add-redis-leader.yml
      vars:
        new_leader_node: "{{ item }}"
      with_items:
        - "{{ groups['leader'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
    - include: add-redis-follower.yml
      vars:
        new_follower_node: "{{ item }}"
      with_items:
        - "{{ groups['follower'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
